### ISSUE TITLE
Sign-up page is very overwhelming - reorder fields

### ISSUE THREAD

**Issue by yankola** [TeamMentor/TM_4_0_Design#1034]
The sign-up page fields are very overwhelming to me because there are so many. I suggest grouping the information a little differently:

_Left Column_
first name, last name, email address, password, confirm password

_Right Column_
username, company, job title, country, state (perhaps country and state as drop downs)

I think Nike does a nice job of spacing out the fields and creating a bit of variety in the way the user can respond:
<img width="893" alt="screen shot 2015-09-23 at 4 07 44 pm" src="https://cloud.githubusercontent.com/assets/12300809/10057408/314db902-620e-11e5-8005-86ddbcc82e69.png">

**Comment by luchia** [comment]
How does this look to everyone?

![screen shot 2015-09-25 at 11 18 53 am](https://cloud.githubusercontent.com/assets/4547737/10090827/3b6363e6-6377-11e5-828f-31c6e534a373.png)

**Comment by luchia** [comment]
Actually, with a little more spacing -

![screen shot 2015-09-25 at 11 31 30 am](https://cloud.githubusercontent.com/assets/4547737/10090965/fe476b4a-6378-11e5-9e14-ec4ae7197e74.png)

**Comment by yankola** [comment]
I think it's looking better. My biggest complaint is that the button is too large. Does anyone else have a suggestion as to how to give this page more variety?

**Comment by romichg** [comment]
I am not sure about username on the right. Username is kinda the first mandatory thing that you want people to put in. Just doesn't feel right on the right :) and yea, I agree, button is definitely oversized.

**Comment by luchia** [comment]
![screen shot 2015-09-26 at 6 29 00 pm](https://cloud.githubusercontent.com/assets/4547737/10116610/7e7d6b58-647c-11e5-928c-dd3e37f62c11.png)

So nice having another designer look at my work. After staring at this thing for 15 months, I don't see what's wrong with it anymore. Open to more suggestions.

**Comment by luchia** [comment]
What does everyone think of this? There's a little bit more breathing room in between the columns.

![screen shot 2015-09-29 at 8 49 24 am](https://cloud.githubusercontent.com/assets/4547737/10151088/4f6b1236-6687-11e5-973b-8314884fa248.png)

**Comment by yankola** [comment]
I think it looks much better!

**Comment by romichg** [comment]
Looks good, do you think we can we group the mandatory fields together somehow? Like username, email and pw are kinda really important.

**Comment by michaelhidalgo** [comment]
HI @luchia , I've fixed the Signup form because this new one did not have the event that should fire when submitting the form. It did not have the alerts so I added them : However, it seems like the alert dialog/div is too large , what do you think?

![screen shot 2015-09-29 at 14 11 03](https://cloud.githubusercontent.com/assets/1732035/10176808/1cd50480-66b4-11e5-9656-f3c14473f99e.png)

**Comment by michaelhidalgo** [comment]
I've sent a PR https://github.com/TeamMentor/TM_Flare/pull/62 to submit the form and show the alerts. @luchia what do you think about the alert?

**Comment by luchia** [comment]
Hi Michael, I added them in my PR today - thank you for your help on this!

@roman87 ordering? I think this is the best way to do it.

![screen shot 2015-09-30 at 8 05 58 am](https://cloud.githubusercontent.com/assets/4547737/10179617/750186ec-674a-11e5-81ce-c47756a8ad55.png)

**Comment by romichg** [comment]
I am still not fond of the ordering but this is probably the best way of doing it for now. My only question, and that is more for @yankola  is - should we change "State" to "State/Province"  you know for all the countries that don't have states.

**Comment by yankola** [comment]
That works for me!

**Comment by romichg** [comment]
@michaelhidalgo should be easy enough. I will make it sprint3 since it is not that important.
