### ISSUE TITLE
Landing page Image missaligned on hires screen

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#531]
![selection_152](https://cloud.githubusercontent.com/assets/1326120/6604839/c506b95c-c801-11e4-8de2-9ea4cddfcef7.png)

**Comment by luchia** [comment]
I did have this problem originally but I fixed it. Do you have the latest version? I can't see what you're seeing -

![screen shot 2015-03-12 at 5 50 11 am](https://cloud.githubusercontent.com/assets/4547737/6605451/d3bde0cc-c87b-11e4-97b8-445da9ebf8f6.png)
![screen shot 2015-03-12 at 5 50 21 am](https://cloud.githubusercontent.com/assets/4547737/6605452/d3cc8d20-c87b-11e4-9e6b-e484e9b7cb2b.png)

I took the border off to check and it lines up perfectly -

![screen shot 2015-03-12 at 5 53 28 am](https://cloud.githubusercontent.com/assets/4547737/6605498/2cd828b6-c87c-11e4-9f75-2cb5aee38eb7.png)
![screen shot 2015-03-12 at 5 54 20 am](https://cloud.githubusercontent.com/assets/4547737/6605508/3f9dd9be-c87c-11e4-823e-b91b4899b8a6.png)

**Comment by michaelhidalgo** [comment]
This has not been merged into Dev, right? I think In Dev I can see what Roman is reporting.

**Comment by luchia** [comment]
Are you on the Lucy branch? I can't see it.

**Comment by michaelhidalgo** [comment]
No, I'm not :),

I got the latest version from Dev. I guess this fix it is still not there :)

2015-03-11 14:43 GMT-06:00 Luchia Bloomfield <notifications@github.com>:

> Are you on the Lucy branch? I can't see it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TeamMentor/TM_4_0_Design/issues/531#issuecomment-78367050>
> .
>



-- 
Michael Hidalgo
http://michaelhidalgocr.blogspot.com

*The future has many names: For the weak, it means the unattainable. For
the fearful, it means the unknown. For the courageous, it means
opportunity. (1802-1885) French Poet, Dramatist, Writer*

**Comment by luchia** [comment]
Okay, that makes sense. It's probably still on the Lucy branch as I kept working on other issues yesterday.

**Comment by DinisCruz** [comment]
I just pushed the latest's Lucy changes into **Dev** branch

![image](https://cloud.githubusercontent.com/assets/656739/6609292/8edaa42e-c847-11e4-8611-32eacea6eb60.png)

**Comment by roman87** [comment]
yep looks like this is fixed.
