### ISSUE TITLE
Article box size issue on search results

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#772]
@luchia can you see what is happening with the 2nd search result

![image](https://cloud.githubusercontent.com/assets/656739/7576743/18074fe2-f839-11e4-9d14-8e27d75b5b3f.png)

**Comment by DinisCruz** [comment]
It looks like it happens when the 'preview' text is small 
![image](https://cloud.githubusercontent.com/assets/656739/7576766/4d226982-f839-11e4-9736-947a68bbc1b6.png)

**Comment by luchia** [comment]
Got it, it was a small fix on the table cell -

![screen shot 2015-05-12 at 9 17 23 am](https://cloud.githubusercontent.com/assets/4547737/7577078/bb4665aa-f887-11e4-8578-8d068f5a7727.png)

**Comment by DinisCruz** [comment]
ok, I just merged the code (into Dev)

**Comment by DinisCruz** [comment]
yap this has been fixed (closing)

**Comment by DinisCruz** [comment]
@luchia you re-introduced this on the latest commit(s)

**Comment by DinisCruz** [comment]
sorry, my mistake, looks fixed

any way @roman @michaelhidalgo and @luchia can you double check?

**Comment by roman87** [comment]
Still an issue:
![selection_227](https://cloud.githubusercontent.com/assets/1326120/7580388/7640d26e-f842-11e4-86a9-8ee3043aba88.png)

**Comment by luchia** [comment]
It's fixed on Dev, I just checked -

![screen shot 2015-05-13 at 7 35 08 am](https://cloud.githubusercontent.com/assets/4547737/7599080/a1ef8a3a-f942-11e4-87d8-bbac98d48665.png)

**Comment by roman87** [comment]
Fixed.
