### ISSUE TITLE
For some reason some accounts show as disabled, even though I can login to the backend

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#958]
![selection_011](https://cloud.githubusercontent.com/assets/1326120/9668735/52df282a-5251-11e5-9e2c-b270f27131e2.png)
![selection_012](https://cloud.githubusercontent.com/assets/1326120/9668740/5770feea-5251-11e5-8dda-b1f5d0f5978e.png)

**Comment by michaelhidalgo** [comment]
hmm that's weird... It is also weird that you see the green and red alerts.

Let me try to reproduce it.

**Comment by romichg** [comment]
Let me know if you want to use my account.

**Comment by michaelhidalgo** [comment]
Hi @roman87  can you please give it a quick test, I believe it has been fixed.

thanks.

**Comment by romichg** [comment]
So far so good. I'll keep it open for a while longer just to make sure there is no race condition anywhere.

**Comment by romichg** [comment]
I just had this happen again. This looks like some sort of race condition in the UI. It seems to happen sometimes only when I am running on battery and have really strong power savings on.

![account-disabled](https://cloud.githubusercontent.com/assets/1326120/9780121/662f395a-5752-11e5-87f8-7f79763db2fd.png)

**Comment by luchia** [comment]
LOL ^^

**Comment by romichg** [comment]
Still having the issue
![selection_048](https://cloud.githubusercontent.com/assets/1326120/9832724/067665a4-5952-11e5-90ed-560a7e5cbd00.png)
Second try worked fine.

**Comment by romichg** [comment]
This is fixed. Great work team!
